name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: my-repo/my-image:${{ github.sha }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@my-ec2-instance "docker pull my-repo/my-image:${{ github.sha }} && \
        docker stop my-container && \
        docker rm my-container && \
        docker run -d --name my-container -p 80:80 my-repo/my-image:${{ github.sha }}"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}