name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
  
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_SECRET }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: jsamm21/terraformflaskapp:${{ github.sha }}

    - name: Deploy to EC2
      run: |
        sudo ssh -i pemkey/terraform-flask-key.pem ec2-54-176-230-161.us-west-1.compute.amazonaws.com "docker pull jsamm21/terraformflaskapp:${{ github.sha }} && \
        docker stop my-container && \
        docker rm my-container && \
        docker run -d --name my-container -p 80:80 jsamm21/terraformflaskapp:${{ github.sha }}"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}