name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
  
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_SECRET }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: jsamm21/terraformflaskapp:${{ github.sha }}

    - name: Git clone the repository
      uses: actions/checkout@v3

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/terraform-flask-key.pem
        chmod 600 ~/.ssh/terraform-flask-key.pem
        cat >>~/.ssh/config <<END
        Host ec2
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/terraform-flask-key.pem
          StrictHostKeyChecking no
        END
      env:
        SSH_HOST: ${{ secrets.HOST_DNS }}
        SSH_USER: ${{ secrets.USERNAME }}
        SSH_KEY: ${{ secrets.EC2_SSH_KEY }} 

    - name: List home directory
      run: ssh ec2 'ls -la'

    - name: SSH into EC2
      id: ssh-into-ec2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}


    - name: Stop and remove existing Docker container
      run: |
        ssh ${{ steps.ssh-into-ec2.outputs.ip }}
          docker stop terraformflaskapp
          docker rm terraformflaskapp


    - name: Start new Docker container
      run: |
        ssh ${{ steps.ssh-into-ec2.outputs.ip }}
          docker run -d --name terraformflaskapp -p 80:5000 jsamm21/terraformflaskapp:${{ env.SHA }}