name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
  
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_SECRET }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: jsamm21/terraformflaskapp:${{ github.sha }}

    - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/github-actions-key
          chmod 600 ~/.ssh/github-actions-key
          cat >>~/.ssh/config <<END
          Host ec2
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/github-actions-key
            StrictHostKeyChecking no
          END
        env:
          SSH_HOST: ${{ secrets.HOST_DNS }}
          SSH_USER: ${{ secrets.USERNAME }}
          SSH_KEY: ${{ secrets.EC2_SSH_KEY }} 
      - name: List home directory
        run: ssh ec2 'ls -la'

    - name: Deploy to EC2
      run: |
        ssh -i ${{ secrets.EC2_SSH_KEY }} ubuntu@ec2-54-176-230-161.us-west-1.compute.amazonaws.com "docker pull jsamm21/terraformflaskapp:${{ github.sha }} && \
        docker stop my-container && \
        docker rm my-container && \
        docker run -d --name my-container -p 80:80 jsamm21/terraformflaskapp:${{ github.sha }}"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}